# Settings  
baseurl = "https://geheffe.github.io/catalogue/"
#baseURL = "/"  # Au lieu de "https://geheffe.github.io/catalogue/"
#relativeURLs = true  # Ajoutez cette ligne (crucial pour les chemins locaux)
publishDir = "public"  # Assurez-vous que c'est bien le dossier de sortie
languageCode = "fr"
title = "Le catalogue de Françoise"
theme = "autophugo"
disableKinds = ["taxonomy", "term"]
#[taxonomies]
#    tag = "tags"
#    category = "categories"

[services]
    [services.googleAnalytics]
        ID = 'G-T2GZF6D03D'
[params]
    # Meta
    description = "Catalogue de Francoise"
    keywords = "autophugo"
    #msvalidate = ""
    #googlesiteverification = ""
    thumb_width = 600
    thumb_quality = 70
    full_width = 1200
    full_quality = 85
    column_count = 2
    #breadcrumb_use_title = false
    #filename_as_phototitle = false
    images_downloadable = false
    images_downloadable_use_orig = false
    #taxonomies_links = false
    
    # Voir "Bout de codes" : autorise html dans le markdown.....     
[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)']]
        [markup.goldmark.renderHooks]
            [markup.goldmark.renderHooks.link]
                enableDefault = true
        [markup.goldmark.renderer]
# sans la commande ci-dessous, le html ne fonctionne pas...
            unsafe = true            
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
    [markup.highlight]
      anchorLineNos = false
      codeFences = true
      guessSyntax = false
      hl_Lines = ''
      hl_inline = false
      lineAnchors = ''
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = true
      style = 'monokai'
      tabWidth = 4
      wrapperClass = 'highlight'      
        
[params.render_hooks.image]
errorLevel = 'warning' # ignore (default), warning, or error (fails the build)
            
[module]
    [module.hugoVersion]
     extended = true 
           
            
